#!/usr/bin/env python3
"""Regenerates GemmaTools.md from the tools actually registered in server.py.

The catalog used to be hand-maintained and drifted badly — it listed tools that
had been renamed or never existed. Run `make tools` after adding or removing an
@mcp.tool() so the doc stays true.
"""

import asyncio
import sys

import server

OUTPUT = "GemmaTools.md"

HEADER = """# Gemma 4 DevOps Agent Tools

MCP tools exposed by `server.py` for the Queued TPU vLLM agent.

> Generated by `make tools` — do not edit by hand. Descriptions come from each
> tool's docstring.

"""


async def build() -> str:
    tools = sorted(await server.mcp.list_tools(), key=lambda t: t.name)
    lines = [HEADER, f"{len(tools)} tools registered.\n\n"]
    for tool in tools:
        doc = (tool.description or "").strip().splitlines()
        summary = doc[0].strip() if doc else "No description."
        lines.append(f"### `{tool.name}`\n\n{summary}\n\n")
    return "".join(lines)


def main() -> int:
    content = asyncio.run(build())
    with open(OUTPUT, "w") as fh:
        fh.write(content)
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
